drop table Movie,
           Actor,
           Sales,
           Director,
           MovieGenre,
           MovieDirector,
           MovieActor,
           MovieRating,
           Review,
           MaxPersonID,
           MaxMovieID